/* Generated By:JavaCC: Do not edit this line. DDLParserConstants.java */
package org.mentalsmash.whadl.descriptions.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DDLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TEXT = 8;
  /** RegularExpression Id. */
  int IDENTIFIER = 9;
  /** RegularExpression Id. */
  int LETTER = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_TEXT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"<[[[\\n\"",
    "<token of kind 7>",
    "\"\\n]]]>\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\".\"",
    "\"#\"",
  };

}
