/* Generated by JTB 1.4.6 */
package org.mentalsmash.whadl.parser.nodes;

import org.mentalsmash.whadl.parser.visitor.*;

/**
 * JTB node class for the production CollectionOperationExpression:<br>
 * Corresponding grammar :<br>
 * f0 -> UnaryExpression()<br>
 * f1 -> ( #0 ( %0 < CONTAINS ><br>
 * .. .. . .. | %1 < UNION ><br>
 * .. .. . .. | %2 < INTERS ><br>
 * .. .. . .. | %3 < SELECT ><br>
 * .. .. . .. | %4 < EACH > ) #1 UnaryExpression() )*<br>
 */
public class CollectionOperationExpression implements INode {

  /** A child node */
  public UnaryExpression f0;

  /** A child node */
  public NodeListOptional f1;

  /** The serial version uid */
  private static final long serialVersionUID = 146L;

  /**
   * Constructs the node with all its children nodes.
   *
   * @param n0 first child node
   * @param n1 next child node
   */
  public CollectionOperationExpression(final UnaryExpression n0, final NodeListOptional n1) {
    f0 = n0;
    f1 = n1;
  }

  /**
   * Accepts the IRetArguVisitor visitor.
   *
   * @param <R> the user return type
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   * @return a user chosen return information
   */
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  /**
   * Accepts the IRetVisitor visitor.
   *
   * @param <R> the user return type
   * @param vis the visitor
   * @return a user chosen return information
   */
  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  /**
   * Accepts the IVoidArguVisitor visitor.
   *
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   */
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  /**
   * Accepts the IVoidVisitor visitor.
   *
   * @param vis the visitor
   */
  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
