/* Generated by JTB 1.4.6 */
package org.mentalsmash.whadl.parser.nodes;

import org.mentalsmash.whadl.parser.visitor.*;

/**
 * JTB node class for the production UnitMemberInstanceEntry:<br>
 * Corresponding grammar :<br>
 * f0 -> < MEMBER ><br>
 * f1 -> Pattern()<br>
 * f2 -> [ #0 "$" #1 < IDENTIFIER > ]<br>
 * f3 -> < LP ><br>
 * f4 -> Pattern()<br>
 * f5 -> < RP ><br>
 * f6 -> < SEMICOLON ><br>
 */
public class UnitMemberInstanceEntry implements INode {

  /** A child node */
  public NodeToken f0;

  /** A child node */
  public Pattern f1;

  /** A child node */
  public NodeOptional f2;

  /** A child node */
  public NodeToken f3;

  /** A child node */
  public Pattern f4;

  /** A child node */
  public NodeToken f5;

  /** A child node */
  public NodeToken f6;

  /** The serial version uid */
  private static final long serialVersionUID = 146L;

  /**
   * Constructs the node with all its children nodes.
   *
   * @param n0 first child node
   * @param n1 next child node
   * @param n2 next child node
   * @param n3 next child node
   * @param n4 next child node
   * @param n5 next child node
   * @param n6 next child node
   */
  public UnitMemberInstanceEntry(final NodeToken n0, final Pattern n1, final NodeOptional n2, final NodeToken n3, final Pattern n4, final NodeToken n5, final NodeToken n6) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
  }

  /**
   * Constructs the node with only its non NodeToken child node(s).
   *
   * @param n0 first child node
   * @param n1 next child node
   * @param n2 next child node
   */
  public UnitMemberInstanceEntry(final Pattern n0, final NodeOptional n1, final Pattern n2) {
    f0 = new NodeToken("member");
    f1 = n0;
    f2 = n1;
    f3 = new NodeToken("(");
    f4 = n2;
    f5 = new NodeToken(")");
    f6 = new NodeToken(";");
  }

  /**
   * Accepts the IRetArguVisitor visitor.
   *
   * @param <R> the user return type
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   * @return a user chosen return information
   */
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  /**
   * Accepts the IRetVisitor visitor.
   *
   * @param <R> the user return type
   * @param vis the visitor
   * @return a user chosen return information
   */
  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  /**
   * Accepts the IVoidArguVisitor visitor.
   *
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   */
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  /**
   * Accepts the IVoidVisitor visitor.
   *
   * @param vis the visitor
   */
  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
