/* Generated by JTB 1.4.6 */
package org.mentalsmash.whadl.parser.nodes;

import org.mentalsmash.whadl.parser.visitor.*;

/**
 * JTB node class for the production UnitInstanceDefinition:<br>
 * Corresponding grammar :<br>
 * f0 -> < UNIT ><br>
 * f1 -> Pattern()<br>
 * f2 -> [ #0 "$" #1 < IDENTIFIER > ]<br>
 * f3 -> < LCP ><br>
 * f4 -> ( UnitInstanceEntry() )*<br>
 * f5 -> < RCP ><br>
 */
public class UnitInstanceDefinition implements INode {

  /** A child node */
  public NodeToken f0;

  /** A child node */
  public Pattern f1;

  /** A child node */
  public NodeOptional f2;

  /** A child node */
  public NodeToken f3;

  /** A child node */
  public NodeListOptional f4;

  /** A child node */
  public NodeToken f5;

  /** The serial version uid */
  private static final long serialVersionUID = 146L;

  /**
   * Constructs the node with all its children nodes.
   *
   * @param n0 first child node
   * @param n1 next child node
   * @param n2 next child node
   * @param n3 next child node
   * @param n4 next child node
   * @param n5 next child node
   */
  public UnitInstanceDefinition(final NodeToken n0, final Pattern n1, final NodeOptional n2, final NodeToken n3, final NodeListOptional n4, final NodeToken n5) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
  }

  /**
   * Constructs the node with only its non NodeToken child node(s).
   *
   * @param n0 first child node
   * @param n1 next child node
   * @param n2 next child node
   */
  public UnitInstanceDefinition(final Pattern n0, final NodeOptional n1, final NodeListOptional n2) {
    f0 = new NodeToken("unit");
    f1 = n0;
    f2 = n1;
    f3 = new NodeToken("{");
    f4 = n2;
    f5 = new NodeToken("}");
  }

  /**
   * Accepts the IRetArguVisitor visitor.
   *
   * @param <R> the user return type
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   * @return a user chosen return information
   */
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  /**
   * Accepts the IRetVisitor visitor.
   *
   * @param <R> the user return type
   * @param vis the visitor
   * @return a user chosen return information
   */
  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  /**
   * Accepts the IVoidArguVisitor visitor.
   *
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   */
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  /**
   * Accepts the IVoidVisitor visitor.
   *
   * @param vis the visitor
   */
  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
