/* Generated by JTB 1.4.6 */
package org.mentalsmash.whadl.descriptions.parser.visitor;

import org.mentalsmash.whadl.descriptions.parser.nodes.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first order.<br>
 * In your "VoidArgu" visitors extend this class and override part or all of these methods.
 *
 * @param <A> The user argument type
 */
public class DepthFirstVoidArguVisitor<A> implements IVoidArguVisitor<A> {


  /*
   * Base nodes classes visit methods (to be overridden if necessary)
   */

  /**
   * Visits a {@link NodeChoice} node, passing it an argument.
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final NodeChoice n, final A argu) {
    n.choice.accept(this, argu);
    return;
  }

  /**
   * Visits a {@link NodeList} node, passing it an argument.
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final NodeList n, final A argu) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this, argu);
    }
    return;
  }

  /**
   * Visits a {@link NodeListOptional} node, passing it an argument.
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final NodeListOptional n, final A argu) {
    if (n.present()) {
      for (final Iterator<INode> e = n.elements(); e.hasNext();) {
        e.next().accept(this, argu);
        }
      return;
    } else
      return;
  }

  /**
   * Visits a {@link NodeOptional} node, passing it an argument.
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final NodeOptional n, final A argu) {
    if (n.present()) {
      n.node.accept(this, argu);
      return;
    } else
    return;
  }

  /**
   * Visits a {@link NodeSequence} node, passing it an argument.
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final NodeSequence n, final A argu) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this, argu);
    }
    return;
  }

  /**
   * Visits a {@link NodeToken} node, passing it an argument.
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final NodeToken n, @SuppressWarnings("unused") final A argu) {
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return;
  }

  /*
   * User grammar generated visit methods (to be overridden if necessary)
   */

  /**
   * Visits a {@link Descriptions} node, whose children are the following :
   * <p>
   * f0 -> EntityDescription()<br>
   * f1 -> ( EntityDescription() )*<br>
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final Descriptions n, final A argu) {
    // f0 -> EntityDescription()
    n.f0.accept(this, argu);
    // f1 -> ( EntityDescription() )*
    n.f1.accept(this, argu);
  }

  /**
   * Visits a {@link EntityDescription} node, whose children are the following :
   * <p>
   * f0 -> EntityId()<br>
   * f1 -> < TEXT ><br>
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final EntityDescription n, final A argu) {
    // f0 -> EntityId()
    n.f0.accept(this, argu);
    // f1 -> < TEXT >
    n.f1.accept(this, argu);
  }

  /**
   * Visits a {@link EntityId} node, whose children are the following :
   * <p>
   * f0 -> < IDENTIFIER ><br>
   * f1 -> ( #0 ( %0 "."<br>
   * .. .. . .. | %1 "#" ) #1 < IDENTIFIER > )*<br>
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final EntityId n, final A argu) {
    // f0 -> < IDENTIFIER >
    n.f0.accept(this, argu);
    // f1 -> ( #0 ( %0 "."
    // .. .. . .. | %1 "#" ) #1 < IDENTIFIER > )*
    n.f1.accept(this, argu);
  }

}
