/* Generated by JTB 1.4.6 */
package org.mentalsmash.whadl.descriptions.parser.visitor;

import org.mentalsmash.whadl.descriptions.parser.nodes.*;

/**
 * All "Ret" visitors must implement this interface.
 * @param <R> The user return information type
 */
public interface IRetVisitor<R> {

  /*
   * Base "Ret" visit methods
   */

  /**
   * Visits a {@link NodeList} node.
   *
   * @param n the node to visit
   * @return the user return information
   */
  public R visit(final NodeList n);

  /**
   * Visits a {@link NodeListOptional} node.
   *
   * @param n the node to visit
   * @return the user return information
   */
  public R visit(final NodeListOptional n);

  /**
   * Visits a {@link NodeOptional} node.
   *
   * @param n the node to visit
   * @return the user return information
   */
  public R visit(final NodeOptional n);

  /**
   * Visits a {@link NodeSequence} node.
   *
   * @param n the node to visit
   * @return the user return information
   */
  public R visit(final NodeSequence n);

  /**
   * Visits a {@link NodeToken} node.
   *
   * @param n the node to visit
   * @return the user return information
   */
  public R visit(final NodeToken n);

  /*
   * User grammar generated visit methods
   */

  /**
   * Visits a {@link Descriptions} node, whose children are the following :
   * <p>
   * f0 -> EntityDescription()<br>
   * f1 -> ( EntityDescription() )*<br>
   *
   * @param n the node to visit
   * @return the user return information
   */
  public R visit(final Descriptions n);

  /**
   * Visits a {@link EntityDescription} node, whose children are the following :
   * <p>
   * f0 -> EntityId()<br>
   * f1 -> < TEXT ><br>
   *
   * @param n the node to visit
   * @return the user return information
   */
  public R visit(final EntityDescription n);

  /**
   * Visits a {@link EntityId} node, whose children are the following :
   * <p>
   * f0 -> < IDENTIFIER ><br>
   * f1 -> ( #0 ( %0 "."<br>
   * .. .. . .. | %1 "#" ) #1 < IDENTIFIER > )*<br>
   *
   * @param n the node to visit
   * @return the user return information
   */
  public R visit(final EntityId n);

}
