#!/bin/bash

COUNTER=0
totalfails=0
totals=0
totalAvgTime=0
while [  $COUNTER -lt $1 ]; do
     let COUNTER=COUNTER+1 
     result=`java -jar lib/WhadlTester.jar $2 $3 $4 $5 | grep ^FAILS`
     failsResult=`echo $result | awk '{print $2}'`
     fails=`echo $failsResult | cut -f1 -d'/'`
     total=`echo $failsResult | cut -f2 -d'/'`
     totalfails=`expr $totalfails + $fails`
     totals=`expr $totals + $total`
     avgTime=`echo $result | awk '{print $3}'`
     maxTime=`echo $result | awk '{print $4}'`
     minTime=`echo $result | awk '{print $5}'`

     #echo AVGTOT: $totalAvgTime AVG: $avgTime MAX: $maxTime MIN: $minTime FAILS: $failsResult

     if [[ $totalAvgTime = 0 ]]; then
	 totalAvgTime=$avgTime
     else
         totalAvgTime=`echo "scale=3; $totalAvgTime + (($avgTime - $totalAvgTime)/$COUNTER)" | bc -l`
     fi
done

echo "TEST RESULT: $totalfails/$totals ("`echo "scale=3;$totalfails/$totals" | bc -l`") AVG. RUN-TIME: "$totalAvgTime

